---
- name: Remove GitHub Actions Runner
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: "github_repository"
      prompt: "Enter your/organization Github repository name"
      private: false
    - name: "runner_name"
      prompt: "Enter runner name"
      private: false
  
  vars:
    runner_dir: actions-runner/{{ github_repository }}/{{ runner_name }}

  pre_tasks:
    - name: Check if the directory exists
      ansible.buildin.stat:
        path: "{{ runner_dir }}"
      register: runner_exists

  tasks:
    - name: Uninstall service
      shell: ./svc.sh uninstall
      args:
        chdir: "{{ runner_dir }}"
      when: runner_exists.stat.exists
    
    - name: Remove .runner file
      shell: rm .runner
      args:
        chdir: "{{ runner_dir }}"
      when: runner_exists.stat.exists

    - name: Remove Github Actions Runner
      shell: ./config.sh remove
      args:
        chdir: "{{ runner_dir }}"
      when: runner_exists.stat.exists
    
    - name: Clean up folders
      shell: rm -rf {{ runner_name }}
      args:
        chdir: "{{ github_repository }}"
      when: runner_exists.stat.exists