---
- name: Setup GitHub Actions Runner on macOS ARM
  hosts: all
  gather_facts: false

  vars_prompt:
    - name: "github_account"
      prompt: "Enter your/organization Github account"
      private: false
    - name: "github_repository"
      prompt: "Enter your/organization Github repository name"
      private: false
    - name: "github_runner_token"
      prompt: "Enter Github runner token (can be found here: https://github.com/ACCOUNT/REPOSITORY/settings/actions/runners/new)"
      private: true
    - name: "runner_name"
      prompt: "Enter unique runner name"
      private: false

  vars:
    runner_version: "2.311.0"
    runner_arch: "arm64"
    runner_dir: actions-runner/{{ github_repository }}/{{ runner_name }}

  tasks:
    - name: Download GitHub Actions Runner
      ansible.builtin.get_url:
        url: "https://github.com/actions/runner/releases/download/v{{ runner_version }}/actions-runner-osx-{{ runner_arch }}-{{ runner_version }}.tar.gz"
        dest: "/tmp/actions-runner.tar.gz"

    - name: Create a directory for the GitHub Runner
      ansible.builtin.file:
        path: "{{ runner_dir }}"
        state: directory

    - name: Extract GitHub Actions Runner
      ansible.builtin.command: tar xzf /tmp/actions-runner.tar.gz -C "{{ runner_dir }}"

    - name: Configure GitHub Actions Runner
      ansible.builtin.command: >
        ./config.sh --url https://github.com/{{ github_account }}/{{ github_repository }}
        --token {{ github_runner_token }}
        --name {{ runner_name }}
        --unattended
        --replace
      args:
        chdir: "{{ runner_dir }}"
        creates: "{{ runner_dir }}/.credentials"

    - name: Install runner as a service
      ansible.builtin.command: ./svc.sh install
      args:
        chdir: "{{ runner_dir }}"

    - name: Start runner service
      ansible.builtin.command: ./svc.sh start
      args:
        chdir: "{{ runner_dir }}"
