name: Auto release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: '>=1.17.0'
      
      - name: Build
        run: |
          cd tagtolibv 
          go build -o bin/tagtolibv
      
      - name: Print results
        run: ls -l tagtolibv